# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker



trigger:
- main

variables:
  dockerRegistryServiceConnection: 'e32a9b69-5126-404f-bd51-32dfd4904bce'
  imageRepository: 'dockerwebapp2026'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  buildConfiguration: 'Release'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:

# SonarCloud Prepare
- task: SonarCloudPrepare@4
  displayName: 'Prepare SonarCloud Analysis'
  inputs:
    SonarQube: 'docker-sonar-devops-service-connection-2026'
    organization: 'nareshcloudworld-org'
    scannerMode: 'dotnet'
    projectKey: 'nareshcloudworld-org_docker-2026-project'
    projectName: 'docker-2026-Project'

# Restore
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    azureSubscription: 'devops-azure-service-connection'
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

# Build
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    azureSubscription: 'devops-azure-service-connection'
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'



# SonarCloud Analyze
- task: SonarCloudAnalyze@4
  displayName: 'Run SonarCloud Analysis'

# SonarCloud Publish
- task: SonarCloudPublish@4
  continueOnError: true
  displayName: 'Publish Quality Gate'
  inputs:
    pollingTimeoutSec: '300'



# Docker Build
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
      latest

# Docker Push
- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    command: 'push'
    repository: $(imageRepository)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)
      latest